site_name: TeraXLang API
site_url: https://deciding.github.io/teraxlang/
repo_url: https://github.com/deciding/teraxlang
site_description: TeraXLang (formerly Triton Xtra Language) API Documentation

theme:
  name: material
  palette:
    - primary: indigo
      accent: blue

nav:
  - Home: index.md
  - API:
      - Core: api/core.md
      - JIT: api/jit.md
